### ISSUE TITLE
How do we delete stale entries from the sheet? 

### ISSUE THREAD

**Issue by naveends** [karthikb351/chennairains.org#8]
Some people want to delete stale entries from the sheet. How do we delete it? Can we get a owner of the sheet we can contact about this?

**Comment by karthikb351** [comment]
Ideally just ping [@sandygrains](https://twitter.com/sandygrains) and [@sowmyarao_](https://twitter.com/sowmyarao_) on Twitter. We have since taken down info on the site, so it is okay.
